language: node_js
branches:
  only:
  - master
before_script: bash ./bin/prepare.sh
script:
- ls -al sample.json
after_success: bash ./bin/deploy.sh
env:
  global:
    secure: MWmYY2ap0Nc2m0JqEJJ5dXHbmi9ituoxla2lJUGQMSXuN2GbRQVJsk721t5luzt0b5mLwle6IvRZCJxlMz/U8V/1KdzvSHaydhklTIIBKSIH+RCLPYQZqQzYUj/JTIr/AS8JiDSzqng+p3jJQqLYg7TmlEjbVZY1GCfUHjdMjegUilvqn7BgguZkeZ0wrqa8WiLoeCKrW3miP4LQLyXBEhMe6VI6TPjssPjMrT5gs9hVL6uaHdmIhe3wesbg3hzh89+k+LdEd/HeY6UwgS17noWE3Cx+DDfZjZrzdTM+jFM6QTR28fZjqzxfE2rBRArbkxtRhPnWniw06Afjb445UZ0cqcKwKHHJveRy2FBrjgMLUXAQXc4iartEiiFggZiOciict6YvJFA2cQzE+2k2/ZsLRilm30QodWq69Lkn2RaBeHo6pOcQ/DSuacbZXFk0JMxEgsdgPE7FY4UdnTAFary2u6+cI5eKuOmum+xO/FfNHp7KBHPetoZhvINhloX+gMAr6PgoMsPWygCIXeJG5E72pf3mt7EA8Wkshw94uH552Js9jxRLZKGHFXOJaiGrjsXN4RseDGxSPVcutbQlUTCgDKc/xv8cRMTM7oqUqPTdOzxu9EF/+5yd/m4P//n6wMstgHKsAHAJgcw21PNX/3YDe1iSUEVXJkYykngLgHw=
